### ISSUE TITLE
Use of mov() in elo.run()

### ISSUE THREAD

**Issue by instantkaffee** [eheinzen/elo#50]
Thx for the great package.

Stupid question:
I have a problem setting where I want to calculate ELO not just by win/tie/loose but also by margin of victory, as the latter values carry information.

I am not sure whether ELO theory allows this, anyway:
Can I use mov() instead of score() in the formula interface of elo.run()?

**Comment by eheinzen** [comment]
Not a dumb question at all.  A few thoughts:

1. The ability to *model* (note: not *adjust for*) margin of victory is kind of a convenient side-effect of `elo.glm()`, `elo.markovchain()`, etc., since all of those (that is, everything but `elo.run()`) use GLMs to predict win/loss; by changing the outcome (y) and the family of the GLM (binomial -> gaussian), it's pretty easy to *model* margin of victory (using `mov()`, as you note).
2. The ELO framework is really designed just to predict wins and losses.  Since it doesn't use a GLM, you can't model margin of victory.  But, it doesn't sound like you want to *model* margin of victory, but rather *adjust for it*.  This you **can** do in `elo.run()`, by using the `k()` function in the formula interface.  In other words, you can reward a team who wins by a lot with a larger ELO update; matchups which are decided by smaller margins can be rewarded a smaller update.  Usually you'll see people log-transform the margin of victory, since a blowout doesn't usually indicate that a team is *that much* better.  Something like this should do the trick then:

```
elo.run(winlosstie ~ team.A + team.B + k(log(abs(marginofvictory) + 1)), data = data)
```

Does that help?

**Comment by instantkaffee** [comment]
Yes this helps, Great answer! Thanks a lot.
