### ISSUE TITLE
Default elo.run parameters

### ISSUE THREAD

**Issue by BenjaminKay** [eheinzen/elo#51]
I don't understand how elo.run handles the initial Elo score for new players.  It appears, based on my experience with running it, that initial.elos defaults to 1500. However, the documentation says that initial.elos defaults to NULL. Please clarify and potentially update the documentation. 

Second and related issue on elo.run defaults. Elo.run seems to default to k=NULL, which matches the documentation. I think it would be more useful if it defaulted to k=16 or 32, more in line with how chess scoring (ICC) works. 

Thank you for a wonderful and useful module.

**Comment by eheinzen** [comment]
Thanks for the questions!  Some thoughts below.

You're right that the default for initial Elos is poorly documented.  I've just pushed an update to fix that.

The default for "k" is to throw an error.  That is, if you don't supply k as an argument or in the formula, `elo.run()` will give an error:
```
> elo.run(score(points.Home, points.Visitor) ~ team.Home + team.Visitor, data = tournament)
 Error in elo::elo.model.frame(formula = score(points.Home, points.Visitor) ~  : 
  'k' is not in 'formula' or specified as an argument. 
```

I think I want to keep it this way; since Elo is used for so many more areas of analysis than just chess, it feels more prudent to me to remain agnostic on the matter and require users to adopt their fields' conventions.
