### ISSUE TITLE
regress function - change in functionality when using group argument

### ISSUE THREAD

**Issue by jimmyday12** [eheinzen/elo#58]
Hi mate - love the package, have been using it for a few years. 

Something I noticed about a recent release was that the functionality of `regress` seems to have changed. Previously - you could provide a logical vector where the regression would happen on games/rows where this vector was `TRUE`. I used to just make the first match of every season for each team set to `TRUE`.

This was in line with the documentation 

> regress() can be used to regress Elos back to a fixed value after certain matches. Giving a logical vector identifies these matches after which to regress back to the mean. Giving any other kind of vector regresses after the appropriate groupings (see, e.g., [duplicated](http://127.0.0.1:44809/help/library/elo/help/duplicated)(..., fromLast = TRUE)). The other three arguments determine what Elo to regress to (to = ), by how much to regress toward that value (by = ), and whether to continue regressing teams which have stopped playing (regress.unused, default = TRUE).

This was working well for a while but started breaking with an error once I updated to the latest version. Using the example from the documentation, slightly adjusted to what I was doing.

``` r
library(elo)
#> Warning: package 'elo' was built under R version 4.0.5

tournament$elo.Visitor <- 1500
tournament$First.Game <- tournament$week == 8

elo.run(score(points.Home, points.Visitor) ~ team.Home + elo.Visitor +
          regress(First.Game, 1500, 0.2) +
          group(week),
        data = tournament, k = 20)
#> Error in check_elo_run_vars(mf, initial.elos): You can't regress mid-group
```

I noticed that if I removed the `group` argument it fixed the error. Similarly, I could keep the `group` argument but change the `regress` column to reference just the `Half` column like in your real example, things worked fine. 

``` r
library(elo)
#> Warning: package 'elo' was built under R version 4.0.5

tournament$elo.Visitor <- 1500

elo.run(score(points.Home, points.Visitor) ~ team.Home + elo.Visitor +
          regress(half, 1500, 0.2) +
          group(week),
        data = tournament, k = 20)
#> 
#> An object of class 'elo.run.regressed', containing information on 8 teams and 56 matches, with 2 regressions.
```

I've got that working fine by updating my code but figured I'd point out the error when using `group` with the logical vector. I'm not sure if this is intentional but it was certainly something that worked fine before and stopped working on updating to the latest version so thought you'd like to know!

**Comment by eheinzen** [comment]
Sorry for the inconvenience!

That change is [on purpose](https://github.com/eheinzen/elo/commit/f50bfa8056d5ca3375c60f31c1f3c1dc00c8f23e): I had to change the meaning of the `group()` function to allow for additional functionality.  From the manpage:
```
?elo::group

`group()` is used to group matches (by, e.g., week). For `elo.run`, Elos are not updated until the group changes. It is also fed to `as.matrix.elo.run`, giving the number of rows to return. to produce only certain rows of matrix output.
```

It's a non-backward-compatible update, which is why I bumped the version to 3.0.0.  To compute Elo updates for every row in the data, you'll want to either (1) omit `group()`--as you note--or (2) pass a logical vector with all `TRUE`'s.

If you *don't* want to compute Elo updates every row, then you can pass `group()` with a logical vector still; however, it won't regress scores until it finishes computing them--at the end of a `group()` period.  In other words, it expects that `regress == TRUE` only if `group == TRUE` as well.

Sorry about that :(
