### ISSUE TITLE
adjust() gives same result

### ISSUE THREAD

**Issue by sebban44** [eheinzen/elo#59]
Hi,
Thanks for a great package. I have been using it a lot but recently started reading up on adjust(). I keep getting same result for elo with adjust as I do without. I am wondering if I am missreading how it should be used?
 Example:
An even game with an added home factor of 10

`
elo.calc(1,adjust(1500,10),1500,k(32))

  elo.A elo.B
1  1516  1484
`

Same without home factor

`
elo.calc(1,1500,1500,k(32))

  elo.A elo.B
1  1516  1484

`

Is the point of adjust() to add/subtract (is negative value even possible?) the adjustment value for every elo calculation? Meaning we add 10 points to the home team?

I am thinking of using adjust() for penalize a players elo if they have not played in x nr of days. Will I need to use a custom prob and func instead?

thanks.

**Comment by eheinzen** [comment]
Nope, you're on the right track: `adjust()` will do what you're looking for.  However that function only works in a formula context; otherwise you have to pass a separate argument.  One of these should work:

```
> # Doesn't work
> # elo.calc(1, adjust(1500,10), 1500, k(32))

> # Does work
> elo.calc(1, 1500, adjust.A = 10, 1500, k(32))
    elo.A   elo.B
1 1515.54 1484.46

> # Also works
> elo.calc(wins ~ adjust(A, 10) + B + k(32), data = data.frame(wins = 1, A = 1500, B = 1500))
    elo.A   elo.B
1 1515.54 1484.46
```

**Comment by sebban44** [comment]
Thanks for the reply Ethan.

Your two examples works, but the trouble I am having is that it wont calculate upon bigger values in adjust

If i get the documentation right, adjust.A/.B should adjust the rankings for A or B from a numeric vector.

Lets say I have player A v player B, A has been absent for x number of days. So we want to adjust his elo ratings to a lower one before this match:

```
#subtracting -100 
elo.calc(wins ~ adjust(A, c(-100)) + B + k(32), data = data.frame(wins = 1, A = 1789, B = 1630))
     elo.A    elo.B
1 1802.309 1616.691

#I was thinking it is calculating it as wins ~ elo.A  + - adjust.A + ...?

#same example with positive value
elo.calc(wins ~ adjust(A, 100) + B + k(32), data = data.frame(wins = 1, A = 1789, B = 1630))
     elo.A    elo.B
1 1794.881 1624.119

#Same here but other way around? wins ~ elo.A + adjust.A + ...?
```

**Comment by eheinzen** [comment]
It works how you think it does.  Perhaps a detailed example will help.

In the first example, your adjustment (-100) is added to the Team A's Elo rating, making it effectively 1689.  Since that score is closer to 1630, it gets a bigger adjustment for having won the match than in the second example, where its Elo is effectively 1889.  That is, when A's Elo is 1889, the Elo ranking systems says "well of course you won, you're the better team, by _a lot_", and so it doesn't reward Team A for having won the match.  On the other side, in the first example, the ranking system says "wow, you must be better than we think because you beat a team that's almost as good as you", so it rewards Team A more for having won the match.

Does that make sense?

**Comment by sebban44** [comment]
Thanks Ethan. I do understand your example better.

I think my misunderstanding was that I thought it would take the adjustment as the new rating to adjust, and that it wouldnt adjust the original rating only.
But that makes sense ,thank you for your answers!
